repos:
  - repo: local
    hooks:
      - id: gdscript-formatter
        name: gdscript-formatter
        description: "formatter for GDScript"
        entry: gdscript-formatter
        language: system
        require_serial: true
        types: [gdscript]

  - repo: local
    hooks:
      - id: gdscript-linter
        name: gdscript-linter
        description: "linter for GDScript"
        entry: gdscript-formatter lint
        language: system
        require_serial: true
        types: [gdscript]
