# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3.45"

tasks:
  create-gd-filepaths-list:
    sources:
      - "**/*.gd"
    generates:
      - .gd_filepaths_list
    cmds:
      - for: sources
        cmd: echo "{{.ITEM}}" >> .gd_filepaths_list

  lint:
    deps:
      - create-gd-filepaths-list
    vars:
      FILES: $(cat .gd_filepaths_list)
    cmds:
      - defer: rm -rf .gd_filepaths_list
      - gdscript-formatter lint --pretty {{.CLI_ARGS}} {{.FILES}}

  format:
    deps:
      - create-gd-filepaths-list
    vars:
      FILES: $(cat .gd_filepaths_list)
    cmds:
      - defer: rm -rf .gd_filepaths_list
      - gdscript-formatter {{.CLI_ARGS}} {{.FILES}}
